### PR TITLE
update to 0.13.1

### PR DESCRIPTION
**Pull request by AlexErrant**
Uh, can you please rebase or merge commit? Maintaining history is pretty important to me for keeping this project up to date - being able to see why I made certain changes (e.g. `"burn-fusion?/defalt"` was commented out simply to make it build). Thanks :)

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
OK, I miss the notification when I worked in #3. I will check this PR soon.

**Comment by L-M-Sherlock** [comment]
```
# jarrettye @ Zen-Max in ~/Codes/open-spaced-repetition/burn/examples/train-web/train on git:fsrs-browser-0.13.1 x [11:18:08] C:1
$ ./build-for-web.sh
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
Error: `cargo metadata` exited with an error: error: failed to parse manifest at `/Users/jarrettye/Codes/open-spaced-repetition/burn/examples/train-web/train/Cargo.toml`

Caused by:
  error inheriting `log` from workspace root manifest's `workspace.dependencies.log`

Caused by:
  failed to find a workspace root

Caused by: `cargo metadata` exited with an error: error: failed to parse manifest at `/Users/jarrettye/Codes/open-spaced-repetition/burn/examples/train-web/train/Cargo.toml`

Caused by:
  error inheriting `log` from workspace root manifest's `workspace.dependencies.log`

Caused by:
  failed to find a workspace root
  ```

**Comment by AlexErrant** [comment]
Ah, I've been ignoring `examples/train-web` repo (and the missing `mnist.db`) because my PR was rejected. I don't really see any advantage to maintaining it since... well, I really only truly care about fsrs-browser. I only added train-web to be a good citizen to Burn :)

Maybe we could delete it? Don't feel strongly about it, am happy doing nothing for now unless you feel differently.

**Comment by L-M-Sherlock** [comment]
If it's unused anymore, it's nice to delete it.

**Review by L-M-Sherlock — APPROVED** [review]

**Pull request merged**
