### PR TITLE
update to the _real_ 0.13.1

### PR DESCRIPTION
**Pull request by AlexErrant**
In [the other merged PR](https://github.com/open-spaced-repetition/burn/pull/2) I thought we were on 0.13.1

That was incorrect.

Anyway, here's the real 0.13.1 update lol

### CODE REVIEW

**Review by L-M-Sherlock — APPROVED** [review]
Trust you, lol.

**Comment by L-M-Sherlock** [comment]
Is there any method solving this?

https://github.com/open-spaced-repetition/fsrs-rs/actions/runs/8856996689/job/24323937269#step:5:41

**Comment by ishiko732** [comment]
> 有什么方法可以解决这个问题吗？
> 
> https://github.com/open-spaced-repetition/fsrs-rs/actions/runs/8856996689/job/24323937269#step:5:41

I think it should be like this...
```diff
- git merge main -m "Auto-merge for $TAG"
+ git merge origin/main -m "Auto-merge for $TAG"
```

**Comment by AlexErrant** [comment]
Ohh, hopefully that's it!

**Pull request merged**
